services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: root
      JWT_ACCESS_SECRET: your-access-secret
      JWT_REFRESH_SECRET: your-refresh-secret
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  pgdata: